# Site settings
title: Tara Ahmed
email: hello@taraahmed.me
description: "Tara Ahmed's official author website. Currently featuring her debut book release, The Marriage Contract."
baseurl: ""
url: "http://taraahmed.me"
twitter_username: authortaraahmed 
facebook_username: authortaraahmed 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]