# Site settings
title: Tara Ahmed.
email: hello@taraahmed.me
description: "Tara Ahmed - Author. Freelance Writer. Freelance Editor. Proofreading and Query Letter Services."
keywords: "Tara, Ahmed, freelance editor, sample edit, freelance writer, editing service, writing service, literary, the marriage contract, manuscript, query letter writing"
baseurl: "http://taraahmed.me"
url: "http://taraahmed.me"
twitter_username: authortaraahmed 
facebook_username: authortaraahmed 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 3
exclude: ["node_modules"]
