# Site settings
title: Tara Ahmed email: hello@taraahmed.me 
description: "Write your site description here. It will be used as your sites meta description as well!"
baseurl: "/"
url: "http://taraahmed.me"
twitter_username: authortaraahmed 
github_username: taraahmed 
facebook_username:  authortaraahmed 

# Build settings
markdown: kramdown
permalink: pretty
paginate: 5
exclude: ["node_modules"]